### ISSUE TITLE
Can't get more than 8 devices connected at the same time

### ISSUE THREAD

**Issue by keanew** [ldrago63/my-hassio-addons#2]
This addon is interesting but when I'm trying to connect more than 8 devices, the hotspot refuses the connection. 
Any ideas ? 
I don't have specific logs or errors.
I have also read on many topics, that the raspberry pi can't accept more than X connections. It depends. It could be 8, 10, 20  etc...
Do you use an external USB wifi dongle ?

**Comment by ldrago63** [comment]
Hi @keanew,

I have just use my addon in small apartment with 4 outlets and 4 cameras maximum. It is possible the raspberry have this limitation.

What is your pi version please ?

**Comment by keanew** [comment]
Hi, 

Thanks for your answer. Hahaha 4 outlets and 4 cameras (8 devices...). Maybe if you try adding one more, you'll have the same problem... :D
It's a Raspberry Pi 4 model B (Quad-core ARMv8 1,5 GHz 64 bits).

**Comment by ldrago63** [comment]
This installation is in a client appartement. 

There is an open issue in : https://github.com/raspberrypi/linux/issues/3010

I think It won't be easy.

**Comment by ldrago63** [comment]
You can try this : https://github.com/raspberrypi/linux/issues/3010#issuecomment-788323744

**Comment by keanew** [comment]
> This installation is in a client appartement.
> 
> There is an open issue in : [raspberrypi/linux#3010](https://github.com/raspberrypi/linux/issues/3010)
> 
> I think It won't be easy.

Yeah I understand. I'm not here for judge your installation. It's just that your installation has exactly the same amount of devices than the limit of 8 devices I have in my raspberry. So you couldn't know. 

Thanks for the link. I have seen this comment too before post my issue here. I'm not an expert so I just want to know if you were aware of this limit and if you have a workaround. 

Thank you anyway :). I will see if I found another way.

**Comment by ldrago63** [comment]
No problem. I precise it is a client installation to say you I can't test immediatly... But, thank for your issue! I know now, If he wants to add a device, he's going to have a problem!

I will follow https://github.com/raspberrypi/linux/issues/3010 and notify you if I found a solution :)

Have a nice day.

**Comment by keanew** [comment]
Ok ok ! Perfect. We keep in touch.

I have done a lot of searches days ago. With your answers, today I've finally ordered a USB Wifi dongle (Ralink RT5370). It could reach up to 189 clients. I will tell you if it works. 

https://www.raspberrypi.org/forums/viewtopic.php?p=548133#p548133

Bye.

**Comment by ldrago63** [comment]
Thank you :) Good test for me.

**Comment by keanew** [comment]
see my comment on this [issue](https://github.com/mattlongman/Hassio-Access-Point/issues/9) for the results of my differents tests
