### ISSUE TITLE
Where do I put the configuration

### ISSUE THREAD

**Issue by preeve9534** [ldrago63/my-hassio-addons#3]
If I add it the example to configuration.yaml the file will not parse because the associated integration cannot be found.

If I add:
```
hassio-wifi-hotspot:
  ...
  ...
```
with the example configuration beneath the integration name then configuration.yaml will not parse.

Now stuck.

**Comment by preeve9534** [comment]
OK. Worked this out.

**Comment by ldrago63** [comment]
Hello,

Put your configuration in supervisor addon configuration after installed. Ok for you ?

**Comment by preeve9534** [comment]
Yep. Got it Lucas. I was being an idiot. Sorry.
P

**Comment by ldrago63** [comment]
You are not an idiot, no problem. Not easy at first ;)
