### ISSUE TITLE
Allow an open WiFi hotspot

### ISSUE THREAD

**Issue by preeve9534** [ldrago63/my-hassio-addons#4]
I have a requirement for an open wireless hotspot on my home assistant node (to support connection of some old HP WiFi printers that can't do WPA-2) but I see that the addon doesn't support this.

I've made some trivial changes which just allow the entry of an empty wpa-passphrase and in this case create on open access point and otherwise revert to the default behaviour.

If you are interested I can submit these as a pull request.

**Comment by ldrago63** [comment]
Hi @preeve9534,

If you want to create the pull request, I will be happy to watch it and accept it :)

**Comment by ldrago63** [comment]
Thank you @preeve9534  for contributing : https://github.com/ldrago63/my-hassio-addons/pull/5
